version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    ports:
      - 27019:27017
